#!/bin/bash

echo "🔧 Stripe Webhook Testing Script"
echo "================================"
echo ""
echo "This script will help you test the webhook integration."
echo ""
echo "Step 1: Start the Stripe CLI webhook forwarding"
echo "Run this command in a separate terminal:"
echo ""
echo "stripe listen --forward-to localhost:3000/api/payment/webhook"
echo ""
echo "Step 2: Copy the webhook signing secret that appears"
echo "It will look like: whsec_xxxxxxxxxxxxxxxxx"
echo ""
echo "Step 3: Update your .env.local file with:"
echo "STRIPE_WEBHOOK_SECRET=\"whsec_xxxxxxxxxxxxxxxxx\""
echo ""
echo "Step 4: Restart your Next.js server"
echo ""
echo "Step 5: Trigger a test event:"
echo "stripe trigger payment_intent.succeeded"
echo ""
echo "Or make a real payment in the frontend."
echo ""
echo "Current webhook secret in .env.local:"
grep STRIPE_WEBHOOK_SECRET .env.local | cut -d'"' -f2 | cut -c1-30
echo "..."
echo ""
echo "If webhooks aren't working, check:"
echo "1. The webhook secret matches exactly"
echo "2. The Stripe CLI is running"
echo "3. The server was restarted after changing .env.local"
echo "4. Check server logs for 'WEBHOOK DEBUG' messages"